[2023-11-11T03:52:08.405+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-11T03:52:08.410+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [queued]>
[2023-11-11T03:52:08.410+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 6
[2023-11-11T03:52:08.417+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): outlier_detection_task> on 2023-11-10 00:00:00+00:00
[2023-11-11T03:52:08.423+0000] {standard_task_runner.py:57} INFO - Started process 882 to run task
[2023-11-11T03:52:08.428+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'preprocessing_v1', 'outlier_detection_task', 'scheduled__2023-11-10T00:00:00+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/***_code.py', '--cfg-path', '/tmp/tmplg_xjfvr']
[2023-11-11T03:52:08.429+0000] {standard_task_runner.py:85} INFO - Job 23: Subtask outlier_detection_task
[2023-11-11T03:52:08.455+0000] {task_command.py:416} INFO - Running <TaskInstance: preprocessing_v1.outlier_detection_task scheduled__2023-11-10T00:00:00+00:00 [running]> on host 27df91229c7e
[2023-11-11T03:52:08.499+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Team 3' AIRFLOW_CTX_DAG_ID='preprocessing_v1' AIRFLOW_CTX_TASK_ID='outlier_detection_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-10T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-10T00:00:00+00:00'
[2023-11-11T03:52:08.500+0000] {datapreprocessing.py:87} INFO - Eliminating outliers...
[2023-11-11T03:52:08.501+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/datapreprocessing.py", line 88, in outlier_elimination
    dataset = pd.read_csv(os.path.join(os.path.dirname(__file__), "../data/X_train_scaling.csv"))
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/dags/src/../data/X_train_scaling.csv'
[2023-11-11T03:52:08.507+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=preprocessing_v1, task_id=outlier_detection_task, execution_date=20231110T000000, start_date=20231111T035208, end_date=20231111T035208
[2023-11-11T03:52:08.515+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 23 for task outlier_detection_task ([Errno 2] No such file or directory: '/opt/airflow/dags/src/../data/X_train_scaling.csv'; 882)
[2023-11-11T03:52:08.564+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-11T03:52:08.575+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
